#ifndef KD_TREE_BASED_FARTHEST_POINT_SAMPLING_INTERVAL_H
#define KD_TREE_BASED_FARTHEST_POINT_SAMPLING_INTERVAL_H


class Interval {
public:
    float low, high;
    Interval();
};


#endif //KD_TREE_BASED_FARTHEST_POINT_SAMPLING_INTERVAL_H
