DATA:
  data_name: support
  data_root: /data/support/downsample0325 
  npoints: 40000
  test_area: 5
  classes: 4
  fea_dim: 12
  voxel_size: 0.04
  voxel_max: 80000
  loop: 30

TRAIN:
  arch: pointtransformer_seg_repro
  use_xyz: True
  sync_bn: False
  ignore_label: 255
  train_gpu: [0, 1, 2, 3]
  workers: 2  # data loader workers
  batch_size: 2  # batch size for training
  batch_size_val: 1  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.5
  epochs: 200
  start_epoch: 0
  step_epoch: 30
  multiplier: 0.1
  momentum: 0.9
  weight_decay: 0.0001
  drop_rate: 0.5
  manual_seed: 7777
  print_freq: 1
  save_freq: 1
  save_path:
  weight:  # path to initial weight (default: none)
  resume:  "exp/support/pt1_repro/model/model_best.pth"  # path to latest checkpoint (default: none)
  evaluate: True  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
  eval_freq: 1
Distributed:
  dist_url: 
  dist_backend:  
  multiprocessing_distributed: False
  world_size: 1
  rank: 0

TEST:
  test_list: 
  test_list_full: 
  split: val  # split in [train, val and test]
  test_gpu: [0]
  test_workers: 4
  batch_size_test: 4
  test_data_root: /data/support/0321/  # /data/support/downsample0325/test
  model_path: exp/support/pt1_repro/model/model_last.pth  # exp/support/pt1_repro/model/model_best_0.9.pth
  save_folder:
  names_path: data/support/support_names.txt
  
